export const ISABELLA_LEARNING_API = [
  {
    id: "learning.ingest",
    domain: "heads",
    method: "POST",
    path: "/api/isabella-learning",
    action: "ingest",
    auth: "sovereign-auth+tenant+execute+consent",
    idempotency: false,
    audit: true,
    status: "implemented" as const,
    description:
      "Ingesta auditable de ejemplos supervisados, episodios, preferencias y procedimientos.",
    requestSchema: "LearningIngestApiSchema",
    responseSchema: "LearningResult",
  },
  {
    id: "learning.retrieve",
    domain: "memory",
    method: "GET|POST",
    path: "/api/isabella-learning",
    action: "retrieve",
    auth: "sovereign-auth+tenant",
    idempotency: false,
    audit: true,
    status: "implemented" as const,
    description: "Recuperación de conocimiento aprendido por conceptos y relevancia.",
    requestSchema: "LearningQueryApiSchema",
    responseSchema: "LearningMemory[]",
  },
  {
    id: "learning.evaluate",
    domain: "heads",
    method: "GET|POST",
    path: "/api/isabella-learning",
    action: "evaluate",
    auth: "sovereign-auth+tenant",
    idempotency: false,
    audit: true,
    status: "implemented" as const,
    description: "Evalúa cobertura y calidad de conocimiento aprendido para una consulta.",
    requestSchema: "LearningEvaluateApiSchema",
    responseSchema: "LearningEvaluation",
  },
  {
    id: "learning.snapshot",
    domain: "memory",
    method: "GET|POST",
    path: "/api/isabella-learning",
    action: "snapshot",
    auth: "sovereign-auth+tenant+read",
    idempotency: false,
    audit: true,
    status: "implemented" as const,
    description: "Obtiene snapshot versionado del estado de aprendizaje para respaldo y auditoría.",
    responseSchema: "LearningSnapshot",
  },
  {
    id: "cognitive-training.train",
    domain: "heads",
    method: "POST",
    path: "/api/isabella-cognitive-training",
    action: "train",
    auth: "sovereign-auth+tenant+execute+consent",
    idempotency: true,
    audit: true,
    status: "implemented" as const,
    description:
      "Entrena Isabella mediante señales semánticas, procedurales, contrastivas, contrafactuales, de recuperación, reflexión, preferencia y multimodales.",
    requestSchema: "CognitiveTrainingSample",
    responseSchema: "CognitiveTrainingResult",
  },
  {
    id: "cognitive-training.batch",
    domain: "heads",
    method: "POST",
    path: "/api/isabella-cognitive-training",
    action: "train-batch",
    auth: "sovereign-auth+tenant+execute+consent",
    idempotency: true,
    audit: true,
    status: "implemented" as const,
    description:
      "Procesa hasta 128 muestras de entrenamiento cognitivo en una operación controlada.",
    requestSchema: "CognitiveTrainingSample[]",
    responseSchema: "CognitiveTrainingBatchResult",
  },
  {
    id: "cognitive-training.evaluate",
    domain: "heads",
    method: "POST",
    path: "/api/isabella-cognitive-training",
    action: "evaluate",
    auth: "sovereign-auth+tenant+read",
    idempotency: false,
    audit: true,
    status: "implemented" as const,
    description: "Evalúa comprensión adquirida sin depender del proveedor de modelo.",
    requestSchema: "{ query: string }",
    responseSchema: "LearningEvaluation",
  },
] as const;
