import { z } from "zod";

export const ClaimStatusSchema = z.enum([
  "PLANNED",
  "DESIGNED",
  "PARTIAL",
  "IMPLEMENTED",
  "TESTED",
  "VERIFIED",
  "PRODUCTION-VERIFIED",
  "FAILED",
  "UNKNOWN",
  "NOT-APPLICABLE",
]);

export type ClaimStatus = z.infer<typeof ClaimStatusSchema>;

export const EvidenceTypeSchema = z.enum([
  "SOURCE_CODE",
  "UNIT_TEST",
  "INTEGRATION_TEST",
  "SECURITY_TEST",
  "CONCURRENCY_TEST",
  "EXTERNAL_AUDIT",
  "DEPLOYMENT_RECORD",
  "HEALTH_CHECK",
  "MONITORING_DATA",
  "INCIDENT_REPORT",
  "ARCHITECTURE_DOCUMENT",
  "ADR",
  "DPIA",
  "DPA",
  "PRIVACY_POLICY",
  "TEST_HITL",
  "POLICY_DOCUMENT",
  "TEST_AUDIT_CHAIN",
  "TEST_CONCURRENCY",
  "WORM_CONFIG",
  "TEST_DATA_HANDLING",
  "GIT_HISTORY",
  "DESIGN_RECORDS",
  "DATED_ARTIFACTS",
]);

export type EvidenceType = z.infer<typeof EvidenceTypeSchema>;

export const ClaimSchema = z.object({
  id: z.string().min(1).max(64),
  title: z.string().min(1).max(256),
  description: z.string().min(1),
  requiredStatus: ClaimStatusSchema,
  evidenceRequired: z.array(EvidenceTypeSchema).default([]),
  controls: z.array(z.string()).default([]),
  category: z.enum([
    "FINANCIAL",
    "SECURITY",
    "DATABASE",
    "AUTH",
    "AUDIT",
    "CI_CD",
    "SUPPLY_CHAIN",
    "ENVIRONMENT",
    "GOVERNANCE",
    "PRIVACY",
    "COMPLIANCE",
    "PERFORMANCE",
    "RELIABILITY",
    "MAINTAINABILITY",
  ]),
  owner: z.string().optional(),
  tags: z.array(z.string()).default([]),
  createdAt: z.string().datetime(),
  updatedAt: z.string().datetime(),
});

export type Claim = z.infer<typeof ClaimSchema>;

export const ClaimsRegistrySchema = z.array(ClaimSchema);

export const DEFAULT_CLAIMS: Claim[] = [
  {
    id: "CLAIM-001",
    title: "Provenance",
    description:
      "Complete provenance chain from conception to deployment with dated artifacts and design records",
    requiredStatus: "VERIFIED",
    evidenceRequired: ["GIT_HISTORY", "DESIGN_RECORDS", "DATED_ARTIFACTS"],
    controls: ["CTRL-001", "CTRL-002", "CTRL-003"],
    category: "GOVERNANCE",
    owner: "Edwin Oswaldo Castillo Trejo",
    tags: ["provenance", "governance", "charter"],
    createdAt: "2026-09-01T00:00:00Z",
    updatedAt: "2026-09-07T00:00:00Z",
  },
  {
    id: "CLAIM-002",
    title: "HITL for high-risk operations",
    description:
      "Human-in-the-loop enforcement for all high-risk operations with approval workflow",
    requiredStatus: "TESTED",
    evidenceRequired: ["SOURCE_CODE", "TEST_HITL", "POLICY_DOCUMENT"],
    controls: ["CTRL-010", "CTRL-011", "CTRL-012"],
    category: "SECURITY",
    owner: "Edwin Oswaldo Castillo Trejo",
    tags: ["hitl", "approval", "human-in-the-loop"],
    createdAt: "2026-09-01T00:00:00Z",
    updatedAt: "2026-09-07T00:00:00Z",
  },
  {
    id: "CLAIM-003",
    title: "Tamper-evident audit",
    description:
      "Cryptographically chained audit log with hash verification and concurrency safety",
    requiredStatus: "VERIFIED",
    evidenceRequired: ["SOURCE_CODE", "TEST_AUDIT_CHAIN", "TEST_CONCURRENCY", "WORM_CONFIG"],
    controls: ["CTRL-020", "CTRL-021", "CTRL-022", "CTRL-023"],
    category: "AUDIT",
    owner: "Edwin Oswaldo Castillo Trejo",
    tags: ["audit", "tamper-evident", "hash-chain", "concurrency"],
    createdAt: "2026-09-01T00:00:00Z",
    updatedAt: "2026-09-07T00:00:00Z",
  },
  {
    id: "CLAIM-004",
    title: "Privacy compliance",
    description: "GDPR/AI Act compliance with DPIA, DPA, and privacy-by-design implementation",
    requiredStatus: "TESTED",
    evidenceRequired: ["DPIA", "DPA", "PRIVACY_POLICY", "TEST_DATA_HANDLING"],
    controls: ["CTRL-030", "CTRL-031", "CTRL-032"],
    category: "PRIVACY",
    owner: "Edwin Oswaldo Castillo Trejo",
    tags: ["privacy", "gdpr", "ai-act", "compliance"],
    createdAt: "2026-09-01T00:00:00Z",
    updatedAt: "2026-09-07T00:00:00Z",
  },
  {
    id: "CLAIM-005",
    title: "Financial atomicity",
    description:
      "All financial mutations execute atomically with double-entry ledger and balance protection",
    requiredStatus: "PRODUCTION-VERIFIED",
    evidenceRequired: [
      "SOURCE_CODE",
      "UNIT_TEST",
      "INTEGRATION_TEST",
      "SECURITY_TEST",
      "CONCURRENCY_TEST",
      "EXTERNAL_AUDIT",
      "DEPLOYMENT_RECORD",
      "HEALTH_CHECK",
      "MONITORING_DATA",
      "INCIDENT_REPORT",
    ],
    controls: ["CTRL-040", "CTRL-041", "CTRL-042", "CTRL-043", "CTRL-044"],
    category: "FINANCIAL",
    owner: "Edwin Oswaldo Castillo Trejo",
    tags: ["financial", "atomic", "ledger", "bookpi"],
    createdAt: "2026-09-01T00:00:00Z",
    updatedAt: "2026-09-07T00:00:00Z",
  },
  {
    id: "CLAIM-006",
    title: "Database authority consolidation",
    description:
      "Single authoritative PostgreSQL database (DATABASE_URL) with Supabase as Identity Provider only",
    requiredStatus: "PRODUCTION-VERIFIED",
    evidenceRequired: [
      "SOURCE_CODE",
      "UNIT_TEST",
      "INTEGRATION_TEST",
      "SECURITY_TEST",
      "CONCURRENCY_TEST",
      "EXTERNAL_AUDIT",
      "DEPLOYMENT_RECORD",
      "HEALTH_CHECK",
      "MONITORING_DATA",
      "INCIDENT_REPORT",
    ],
    controls: ["CTRL-050", "CTRL-051", "CTRL-052"],
    category: "DATABASE",
    owner: "Edwin Oswaldo Castillo Trejo",
    tags: ["database", "authority", "postgresql", "supabase"],
    createdAt: "2026-09-01T00:00:00Z",
    updatedAt: "2026-09-07T00:00:00Z",
  },
  {
    id: "CLAIM-007",
    title: "Sovereign state transactional persistence",
    description:
      "SovereignDB uses transactional PostgreSQL persistence with BEGIN/VALIDATE/LOCK/MUTATE/LEDGER/AUDIT/COMMIT pattern",
    requiredStatus: "PRODUCTION-VERIFIED",
    evidenceRequired: [
      "SOURCE_CODE",
      "UNIT_TEST",
      "INTEGRATION_TEST",
      "SECURITY_TEST",
      "CONCURRENCY_TEST",
      "EXTERNAL_AUDIT",
      "DEPLOYMENT_RECORD",
      "HEALTH_CHECK",
      "MONITORING_DATA",
      "INCIDENT_REPORT",
    ],
    controls: ["CTRL-060", "CTRL-061", "CTRL-062"],
    category: "DATABASE",
    owner: "Edwin Oswaldo Castillo Trejo",
    tags: ["sovereign", "transactional", "persistence"],
    createdAt: "2026-09-01T00:00:00Z",
    updatedAt: "2026-09-07T00:00:00Z",
  },
  {
    id: "CLAIM-008",
    title: "Kill switch durable with approval store",
    description:
      "Kill switch uses durable PostgreSQL approval store in production, not in-memory Map",
    requiredStatus: "TESTED",
    evidenceRequired: [
      "SOURCE_CODE",
      "UNIT_TEST",
      "INTEGRATION_TEST",
      "SECURITY_TEST",
      "CONCURRENCY_TEST",
    ],
    controls: ["CTRL-070", "CTRL-071"],
    category: "SECURITY",
    owner: "Edwin Oswaldo Castillo Trejo",
    tags: ["kill-switch", "emergency", "approval-store"],
    createdAt: "2026-09-01T00:00:00Z",
    updatedAt: "2026-09-07T00:00:00Z",
  },
  {
    id: "CLAIM-009",
    title: "MFA step-up for SovereignOwner",
    description: "Privileged operations require MFA step-up authentication",
    requiredStatus: "PLANNED",
    evidenceRequired: [
      "SOURCE_CODE",
      "UNIT_TEST",
      "INTEGRATION_TEST",
      "SECURITY_TEST",
      "CONCURRENCY_TEST",
      "EXTERNAL_AUDIT",
      "DEPLOYMENT_RECORD",
      "HEALTH_CHECK",
      "MONITORING_DATA",
      "INCIDENT_REPORT",
    ],
    controls: ["CTRL-080", "CTRL-081"],
    category: "AUTH",
    owner: "Edwin Oswaldo Castillo Trejo",
    tags: ["mfa", "step-up", "sovereign-owner"],
    createdAt: "2026-09-01T00:00:00Z",
    updatedAt: "2026-09-07T00:00:00Z",
  },
  {
    id: "CLAIM-010",
    title: "CSP hardened without unsafe-inline",
    description:
      "Content Security Policy enforced without 'unsafe-inline', using nonce-based script loading",
    requiredStatus: "TESTED",
    evidenceRequired: ["SOURCE_CODE", "UNIT_TEST", "INTEGRATION_TEST", "SECURITY_TEST"],
    controls: ["CTRL-090", "CTRL-091"],
    category: "SECURITY",
    owner: "Edwin Oswaldo Castillo Trejo",
    tags: ["csp", "content-security-policy", "nonce"],
    createdAt: "2026-09-01T00:00:00Z",
    updatedAt: "2026-09-07T00:00:00Z",
  },
];

export function validateClaim(claim: unknown): Claim {
  return ClaimSchema.parse(claim);
}

export function validateClaimsRegistry(claims: unknown): Claim[] {
  return ClaimsRegistrySchema.parse(claims);
}
