import { createHash } from "node:crypto";

export type KnowledgeDomain =
  | "factual"
  | "technical"
  | "scientific"
  | "security"
  | "ethical"
  | "operational"
  | "creative"
  | "temporal";

export type EvidenceLevel = "E0" | "E1" | "E2" | "E3" | "E4";
export type EpistemicState = "SUPPORTED" | "PROBABLE" | "CONTESTED" | "UNKNOWN";

export interface KnowledgeObservation {
  teacherId: string;
  modelId: string;
  domain: KnowledgeDomain;
  claim: string;
  evidenceLevel: EvidenceLevel;
  confidence: number;
  freshness: number;
  provenanceHash: string;
}

export interface ConvergenceResult {
  state: EpistemicState;
  consensusScore: number;
  evidenceScore: number;
  freshnessScore: number;
  confidenceScore: number;
  diversityScore: number;
  disagreementScore: number;
  selectedClaim: string | null;
  participatingTeachers: string[];
  rejectedTeachers: string[];
  rationale: string[];
  resultHash: string;
}

const EVIDENCE_WEIGHT: Record<EvidenceLevel, number> = {
  E0: 0.15,
  E1: 0.35,
  E2: 0.55,
  E3: 0.78,
  E4: 1,
};

function clamp(value: number): number {
  return Math.max(0, Math.min(1, value));
}

function hash(value: unknown): string {
  return createHash("sha256").update(JSON.stringify(value)).digest("hex");
}

function normalizedClaim(claim: string): string {
  return claim.normalize("NFKC").trim().toLocaleLowerCase("es-MX");
}

function tokenizeClaim(claim: string): Set<string> {
  return new Set(normalizedClaim(claim).split(/\s+/u).filter(Boolean));
}

function cosineFromSets(a: Set<string>, b: Set<string>): number {
  if (!a.size || !b.size) return 0;
  let intersection = 0;
  for (const token of a) if (b.has(token)) intersection++;
  return intersection / Math.sqrt(a.size * b.size);
}

function unknownResult(
  reason: string,
  observations: readonly KnowledgeObservation[],
): ConvergenceResult {
  const participatingTeachers = observations.map((item) => item.teacherId).filter(Boolean);
  const rationale = [reason, "No se fabricó ni aceptó evidencia sintética como segundo maestro."];
  return {
    state: "UNKNOWN",
    consensusScore: 0,
    evidenceScore: 0,
    freshnessScore: 0,
    confidenceScore: 0,
    diversityScore: new Set(participatingTeachers).size / Math.max(1, participatingTeachers.length),
    disagreementScore: 1,
    selectedClaim: null,
    participatingTeachers,
    rejectedTeachers: [],
    rationale,
    resultHash: hash({
      reason,
      observations: observations.map((item) => item.provenanceHash).sort(),
    }),
  };
}

/**
 * Deterministic O(n²) convergence for small teacher sets. The intended hot path
 * is 3-16 observations; it avoids model inference and network calls entirely.
 *
 * Evidence integrity rule: observations generated by validator/baseline identities
 * are never treated as independent teachers. A second observation must originate
 * from an actual independent teacher/model path.
 */
export function convergeKnowledge(
  observations: readonly KnowledgeObservation[],
): ConvergenceResult {
  if (observations.length < 2) {
    return unknownResult("convergence_requires_multiple_observations", observations);
  }
  if (observations.length > 32) throw new Error("convergence_batch_too_large");

  const valid = observations.filter(
    (item) =>
      item.teacherId.length > 0 &&
      item.modelId.length > 0 &&
      item.claim.length > 0 &&
      Number.isFinite(item.confidence) &&
      Number.isFinite(item.freshness) &&
      item.confidence >= 0 &&
      item.confidence <= 1 &&
      item.freshness >= 0 &&
      item.freshness <= 1 &&
      /^[a-f0-9]{64}$/u.test(item.provenanceHash),
  );
  if (valid.length < 2) return unknownResult("insufficient_valid_observations", valid);

  const syntheticValidatorObservations = valid.filter((item) =>
    /(?:^|_)validator(?:_|$)/u.test(item.teacherId),
  );
  if (syntheticValidatorObservations.length > 0) {
    return unknownResult("synthetic_validator_observation_rejected", valid);
  }

  const teacherIds = valid.map((item) => item.teacherId);
  if (new Set(teacherIds).size !== teacherIds.length) {
    return unknownResult("duplicate_teacher_identity_rejected", valid);
  }

  // Tokenize every claim once and evaluate each pair a single time (symmetric
  // similarity). This preserves the original summation order per index, so the
  // deterministic scores are bit-for-bit identical to the previous O(n²) scan.
  const tokenSets = valid.map((item) => tokenizeClaim(item.claim));
  const size = valid.length;
  const similarityMatrix: number[][] = Array.from({ length: size }, () =>
    new Array<number>(size).fill(0),
  );
  for (let i = 0; i < size; i++) {
    for (let j = i + 1; j < size; j++) {
      const value = cosineFromSets(tokenSets[i]!, tokenSets[j]!);
      similarityMatrix[i]![j] = value;
      similarityMatrix[j]![i] = value;
    }
  }

  const scored = valid.map((observation, index) => {
    let similarity = 0;
    for (let i = 0; i < size; i++) {
      if (i === index) continue;
      similarity += similarityMatrix[index]![i]!;
    }
    const agreement = size > 1 ? similarity / (size - 1) : 0;
    const evidence = EVIDENCE_WEIGHT[observation.evidenceLevel];
    const score = clamp(
      0.38 * agreement +
        0.27 * evidence +
        0.2 * observation.confidence +
        0.15 * observation.freshness,
    );
    return { observation, score, agreement };
  });

  scored.sort((a, b) => b.score - a.score);
  const winner = scored[0]!;
  const second = scored[1]!;
  const disagreementScore = clamp(1 - second.agreement);
  const consensusScore = clamp(0.65 * winner.agreement + 0.35 * (1 - disagreementScore));
  const evidenceScore = clamp(
    scored.reduce((sum, item) => sum + EVIDENCE_WEIGHT[item.observation.evidenceLevel], 0) /
      scored.length,
  );
  const freshnessScore =
    scored.reduce((sum, item) => sum + item.observation.freshness, 0) / scored.length;
  const confidenceScore =
    scored.reduce((sum, item) => sum + item.observation.confidence, 0) / scored.length;
  const diversityScore =
    new Set(scored.map((item) => item.observation.teacherId)).size / scored.length;

  const state: EpistemicState =
    consensusScore >= 0.78 && evidenceScore >= 0.7
      ? "SUPPORTED"
      : consensusScore >= 0.58 && evidenceScore >= 0.5
        ? "PROBABLE"
        : consensusScore < 0.35
          ? "CONTESTED"
          : "UNKNOWN";

  const selectedClaim = state === "CONTESTED" ? null : winner.observation.claim;
  const participatingTeachers = scored
    .filter((item) => item.agreement >= 0.45)
    .map((item) => item.observation.teacherId);
  const rejectedTeachers = scored
    .filter((item) => item.agreement < 0.45)
    .map((item) => item.observation.teacherId);
  const rationale = [
    `consensus=${consensusScore.toFixed(4)}`,
    `evidence=${evidenceScore.toFixed(4)}`,
    `freshness=${freshnessScore.toFixed(4)}`,
    `confidence=${confidenceScore.toFixed(4)}`,
    `diversity=${diversityScore.toFixed(4)}`,
    `disagreement=${disagreementScore.toFixed(4)}`,
  ];

  const resultHash = hash({
    state,
    selectedClaim,
    participants: participatingTeachers,
    observations: valid.map((item) => item.provenanceHash).sort(),
    rationale,
  });

  return {
    state,
    consensusScore,
    evidenceScore,
    freshnessScore,
    confidenceScore,
    diversityScore,
    disagreementScore,
    selectedClaim,
    participatingTeachers,
    rejectedTeachers,
    rationale,
    resultHash,
  };
}
